### ISSUE TITLE
Deploying git2consul in Kubernetes

### ISSUE THREAD

**Issue by cdelpinogeo** [Cimpress-MCP/docker-git2consul#5]
Hello,

I am trying to deploy the docker-git2consul container to kubernetes, but I have been unsuccessful in doing so. I am getting the following error when I try to deploy it:

`2016-10-17T20:55:12.227582278Z Config value is not valid JSON: undefined`

Here is the yaml file I created to deploy to kubernetes:

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: git2consul
  labels:
    app: git2consul
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: git2consul
    spec:
      containers:
      - name: git2consul
        image: cimpress/git2consul
        env:
        - name: config_file
          value: '{"version":"1.0","repos [{"name":"config","url":"https://user:password@github.com:org/repo.git","branches":["master"],"hooks":[{"type":"polling","interval":"1"}]}]}'
        - name: endpoint
          value: "10.244.4.241"
        - name: port
          value: "8500"
```
